import { describe, it, expect, vi, beforeEach } from "vitest";
import { ImportService } from "@/services/import.service";
import { ExportService } from "@/services/export.service";
import { BiometricApiService } from "@/services/biometric-api.service";
import { prisma } from "@/lib/prisma";
import JSZip from "jszip";

vi.mock("@/services/biometric-api.service", () => ({
  BiometricApiService: {
    enrollFace: vi.fn().mockResolvedValue({ success: true, model: "insightface" }),
  },
}));

vi.mock("@/lib/prisma", () => ({
  prisma: {
    person: {
      findUnique: vi.fn(),
      findFirst: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
    },
    eventParticipant: {
      findFirst: vi.fn(),
      findUnique: vi.fn(),
      create: vi.fn(),
    },
    user: {
      findUnique: vi.fn().mockResolvedValue({ id: "usr-1", name: "Operador" }),
    },
    auditLog: {
      create: vi.fn().mockResolvedValue({}),
    },
  },
}));

describe("ImportService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("should parse CSV buffer and normalize diverse column names", async () => {
    const csvData =
      "Nome Completo,Matricula,CPF,E-mail,Telefone,Categoria,Observacoes\n" +
      "Lucas Mendes,20265001,111.222.333-44,lucas@unifap.br,(88) 9999-8888,Aluno,Engenharia\n" +
      "Fernanda Lima,20265002,55566677788,fernanda@unifap.br,,Professor,Palestrante";

    const buffer = Buffer.from(csvData, "utf-8");
    const rows = await ImportService.parseFile(buffer, "participantes.csv");

    expect(rows).toHaveLength(2);
    expect(rows[0].name).toBe("Lucas Mendes");
    expect(rows[0].registration).toBe("20265001");
    expect(rows[0].cpf).toBe("11122233344");
    expect(rows[0].category).toBe("Aluno");

    expect(rows[1].name).toBe("Fernanda Lima");
    expect(rows[1].cpf).toBe("55566677788");
    expect(rows[1].category).toBe("Professor");
  });

  it("should reject rows missing category or missing both registration and CPF in processImport", async () => {
    vi.mocked(prisma.person.findUnique).mockResolvedValue(null);
    vi.mocked(prisma.person.create).mockResolvedValue({ id: "p-1" } as any);

    const rows = [
      { name: "Pessoa Sem Categoria", registration: "2026001", cpf: "12345678901" }, // falta categoria
      { name: "Pessoa Sem Doc", category: "Aluno" }, // falta reg e cpf
      { name: "Pessoa Valida", registration: "2026002", category: "Aluno" }, // valida
    ];

    const result = await ImportService.processImport({ rows: rows as any });

    expect(result.totalRows).toBe(3);
    expect(result.errors).toHaveLength(2);
    expect(result.errors[0].error).toContain("Categoria");
    expect(result.errors[1].error).toContain("Matrícula");
    expect(result.createdPersons).toBe(1);
  });

  it("should parse XLSX buffer generated by ExportService", async () => {
    const data = [
      { Nome: "Carlos Alberto", CPF: "12345678901", Matricula: "MAT001", Categoria: "Docente" },
      { Nome: "Mariana Souza", CPF: "98765432100", Matricula: "MAT002", Categoria: "Discente" },
    ];

    const xlsxBuffer = await ExportService.toXlsx(data, "Participantes");
    const rows = await ImportService.parseFile(xlsxBuffer, "participantes.xlsx");

    expect(rows).toHaveLength(2);
    expect(rows[0].name).toBe("Carlos Alberto");
    expect(rows[0].registration).toBe("MAT001");
    expect(rows[0].category).toBe("Docente");
    expect(rows[1].name).toBe("Mariana Souza");
    expect(rows[1].registration).toBe("MAT002");
    expect(rows[1].category).toBe("Discente");
  });

  it("should process ZIP package containing spreadsheet and photos", async () => {
    const zip = new JSZip();
    const csvContent =
      "Nome,Matricula,CPF,Categoria\n" +
      "Aluno Um,20261001,11122233344,Aluno\n" +
      "Aluno Dois,20261002,55566677788,Aluno";

    zip.file("participantes.csv", csvContent);
    zip.file("fotos/20261001.jpg", Buffer.from([0xff, 0xd8, 0xff, 0xe0]));
    zip.file("fotos/20261002.jpg", Buffer.from([0xff, 0xd8, 0xff, 0xe0]));
    zip.file("fotos/desconhecido.jpg", Buffer.from([0xff, 0xd8, 0xff, 0xe0]));

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    const createdPeople: Record<string, any> = {};

    (vi.mocked(prisma.person.findUnique) as any).mockImplementation(async (args: any) => {
      if (args?.where?.registration) {
        return createdPeople[args.where.registration] || null;
      }
      if (args?.where?.cpf) {
        return createdPeople[args.where.cpf] || null;
      }
      return null;
    });

    (vi.mocked(prisma.person.create) as any).mockImplementation(async (args: any) => {
      const p = {
        id: `p-${Object.keys(createdPeople).length + 1}`,
        name: args.data.name,
        registration: args.data.registration,
        cpf: args.data.cpf,
        category: args.data.category,
      };
      if (p.registration) createdPeople[p.registration] = p;
      if (p.cpf) createdPeople[p.cpf] = p;
      return p;
    });

    (vi.mocked(prisma.person.update) as any).mockResolvedValue({});

    const result = await ImportService.processZipPackage({
      buffer: zipBuffer,
      operatorUserId: "usr-1",
    });

    expect(result.totalRows).toBe(2);
    expect(result.createdPersons).toBe(2);
    expect(result.totalPhotos).toBe(3);
    expect(result.photosEnrolled).toBe(2);
    expect(result.photoErrors).toHaveLength(1);
    expect(result.photoErrors[0].filename).toBe("desconhecido.jpg");
    expect(BiometricApiService.enrollFace).toHaveBeenCalledTimes(2);
  });
});
